language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: ekYY9dV27Eqc13pIoag6Nlcc12gO8CuEq74CV9IU7PuExUbtLyLeInkvwvKojEhjgH2uwviFeginSPzhxeu/kqCbx8GRP/E/0c3MhIyboat9MzdguplWy2WL5FvpOVL3p5pXcEch9aD5/0g/IavJqbwN8LErxUfbei0j+p9W968kT8MDWb2ms9RFYlExf4cT/KcBsD7jXWLATNe491+Sj7cTApgvF9awtHdHEMI7XKYFPKHQhaCh7MthiLVesvDP7L5Hq/Oru5FxMaLE1aki4ZuF2rR27AtWIgr081tVbsJ8P2/w24zA9K279WT0/hKQxp4IHlPIxOktI0ygAJR2ta/PIYrb/Yfk5dyeNYw4ZmeI2jPNwuUhBTMRiXdDXUsJRewt/tkjUniF42pTZwlUc9FXit0Xk0jt/w2YMT2w26H3khUV3atvx0FaP5x7oXXxyaNsMroE3PdMWkYojRoK3z130zor8pTmePZLXNyaoMaKehJyikUKVXEHBgyfzete+VVhQFUM/onml3baunLH2Dslf+KhVJn8Grl9GCI3RXkPXPwWC2P5/95eeNQWtK9J3l02b6jW8nd/3WAOji6niXgWbiB+4T8A5B3AxInQIG7hBiEo+fcG8gK7+1T0zxpoNw/70FPU3x4b29VUG4OTbQt1BrW09jxXExVEJmxqiEU=
